import { Kategorie, Produkt } from './models';

export const KATEGORIE: Kategorie[] = [
  { id: 'yellow-friday', nazev: '00. YELLOW FRIDAY (Slevy)' },
  { id: 'novinky', nazev: '01. NOVINKY' },
  { id: 'plachty', nazev: '02. PLACHTY / CEDULE / STOJANY' },
  { id: 'vizitky', nazev: '03. VIZITKY' },
  { id: 'propagace', nazev: '04. PROPAGACE / REKLAMNÍ PŘEDMĚTY' },
  { id: 'letaky', nazev: '05. LETÁKY / BROŽURY' },
  { id: 'deti', nazev: '06. DĚTI' },
  { id: 'kancelar', nazev: '07. KANCELÁŘSKÉ POTŘEBY' },
  { id: 'sport', nazev: '08. SPORT' },
  { id: 'textil', nazev: '10. TEXTIL' },
  { id: 'elektronika', nazev: '12. ELEKTRONIKA' },
];

const VELIKOSTI = ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL', '5XL'];

export const PRODUKTY: Produkt[] = [
  {
    id: 'privesek-stinger',
    kod: 'AFH000036',
    nazev: '3D přívěšek STINGER ke klíčům',
    popis: 'Gumový 3D přívěšek s maskotem STINGER a QR kódem na zadní straně.',
    kategorieId: 'propagace',
    cena: 22,
    skladem: 516,
    stitky: ['novinka'],
    obrazky: ['img/privesek.svg', 'img/bonbony-zlute.svg'],
    dokumenty: [
      { nazev: 'Grafický manuál maskota STINGER', typ: 'pdf', url: '#' },
    ],
    lzePlatitKreditem: true,
  },
  {
    id: 'stojan-pole',
    kod: 'AED000102',
    nazev: 'A stojan do pole 2,5 × 1,25 m',
    popis: 'Venkovní oboustranný stojan pro plachty. Konstrukce z pozinkované oceli.',
    kategorieId: 'plachty',
    cena: 12879.24,
    skladem: 2,
    stitky: [],
    obrazky: ['img/stojan.svg', 'img/plachta.svg'],
    dokumenty: [
      { nazev: 'Montážní návod stojanu', typ: 'pdf', url: '#' },
      { nazev: 'Technický list – rozměry a kotvení', typ: 'pdf', url: '#' },
    ],
    lzePlatitKreditem: true,
  },
  {
    id: 'tricko-bile',
    kod: 'ATX000010',
    nazev: 'Bílé unisex bavlněné tričko',
    popis: '100% bavlna, gramáž 160 g/m². Potisk STING na zádech. Velikost vyberte při vložení do košíku.',
    kategorieId: 'textil',
    cena: 295,
    skladem: 109,
    stitky: ['novinka'],
    obrazky: ['img/tricko.svg', 'img/tricko-zada.svg'],
    dokumenty: [
      { nazev: 'Velikostní tabulka triček', typ: 'pdf', url: '#' },
      { nazev: 'Náhledy potisků', typ: 'odkaz', url: '#' },
    ],
    varianty: { nazev: 'Velikost', hodnoty: VELIKOSTI },
    lzePlatitKreditem: true,
  },
  {
    id: 'plachta-vyber',
    kod: 'AED000039',
    nazev: 'Plachta – grafika a rozměr dle vašeho výběru',
    popis:
      'Napište do poznámky přesný rozměr plachty a zadejte číslo grafiky z dokumentu níže. Cena plachty za 1 m² je 203 Kč plus dopravné 180 Kč.',
    kategorieId: 'plachty',
    cena: 0,
    skladem: 'dodavatel',
    stitky: ['novinka', 'tip'],
    obrazky: ['img/plachta.svg', 'img/stojan.svg'],
    dokumenty: [
      { nazev: 'Náhledy plachet (typové grafiky)', typ: 'pdf', url: '#' },
      { nazev: 'Ceník plachet a dopravy', typ: 'xlsx', url: '#' },
    ],
    lzePlatitKreditem: true,
  },
  {
    id: 'vizitky-standard',
    kod: 'AVZ000005',
    nazev: 'Vizitky STING – standardní šablona',
    popis: 'Oboustranné vizitky 90×50 mm, 300 g křída, mat. Do poznámky uveďte jméno, pozici a kontakty.',
    kategorieId: 'vizitky',
    cena: 240,
    skladem: 'dodavatel',
    stitky: ['tip'],
    obrazky: ['img/vizitky.svg'],
    dokumenty: [
      { nazev: 'Šablony vizitek (typové vzory)', typ: 'pdf', url: '#' },
      { nazev: 'Formulář pro podklady', typ: 'docx', url: '#' },
    ],
    varianty: { nazev: 'Počet kusů', hodnoty: ['100 ks', '200 ks', '500 ks'] },
    lzePlatitKreditem: true,
  },
  {
    id: 'bonbony-cerne',
    kod: 'APR000021',
    nazev: 'Bonbony černé',
    kategorieId: 'propagace',
    cena: 4.37,
    skladem: 1672,
    stitky: [],
    obrazky: ['img/bonbony-cerne.svg'],
    dokumenty: [],
    lzePlatitKreditem: true,
  },
  {
    id: 'bonbony-zlute',
    kod: 'APR000022',
    nazev: 'Bonbony žluté',
    kategorieId: 'propagace',
    cena: 4.37,
    skladem: 1112,
    stitky: ['akce'],
    obrazky: ['img/bonbony-zlute.svg'],
    dokumenty: [],
    lzePlatitKreditem: true,
  },
  {
    id: 'bublifuk',
    kod: 'ADE000008',
    nazev: 'Bublifuk STING',
    kategorieId: 'deti',
    cena: 18.73,
    skladem: 165,
    stitky: ['novinka'],
    obrazky: ['img/bublifuk.svg'],
    dokumenty: [],
    lzePlatitKreditem: true,
  },
  {
    id: 'butylka',
    kod: 'APR000030',
    nazev: 'Butylka nerezová v papírové krabičce',
    kategorieId: 'propagace',
    cena: 339.38,
    skladem: 88,
    stitky: [],
    obrazky: ['img/butylka.svg'],
    dokumenty: [{ nazev: 'Návod na gravírování loga', typ: 'pdf', url: '#' }],
    lzePlatitKreditem: true,
  },
];
